--1
SELECT DEPARTMENT_NAME AS "학과 명" , CATEGORY AS "계열"
FROM TB_DEPARTMENT td ;

--2
SELECT DEPARTMENT_NAME || '의 정원은 ' || CAPACITY || '명 입니다.' AS "학과 별 정원"
FROM TB_DEPARTMENT;

--3
SELECT STUDENT_NAME 
FROM TB_STUDENT ts 
WHERE ABSENCE_YN ='Y' AND DEPARTMENT_NO ='001' AND SUBSTR(STUDENT_SSN,8,1)='2';

--4
SELECT STUDENT_NAME 
FROM TB_STUDENT ts 
WHERE 
(STUDENT_NO= 'A513079'
OR STUDENT_NO ='A513090'
OR STUDENT_NO ='A513091'
OR STUDENT_NO = 'A513110'
OR STUDENT_NO = 'A513119');

--5

SELECT DEPARTMENT_NAME, CATEGORY
FROM TB_DEPARTMENT td 
WHERE CAPACITY BETWEEN 20 AND 30;



--6
SELECT PROFESSOR_NAME
FROM TB_PROFESSOR tp 
WHERE DEPARTMENT_NO IS NULL;


--7

SELECT STUDENT_NAME
FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO IS NULL;


--8
SELECT CLASS_NO
FROM TB_CLASS tc 
WHERE PREATTENDING_CLASS_NO IS NOT NULL;



--9

SELECT DISTINCT CATEGORY
FROM TB_DEPARTMENT td 
ORDER BY CATEGORY ; --카테고리 명으로 정렬해야 함


--10

SELECT  STUDENT_NO , STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT ts 
WHERE ABSENCE_YN ='N' AND EXTRACT(YEAR FROM ENTRANCE_DATE) = '2002' AND STUDENT_ADDRESS LIKE '전주%' ;


