--1
SELECT STUDENT_NAME, STUDENT_ADDRESS 
FROM TB_STUDENT ts 
ORDER BY STUDENT_NAME ;

--2
SELECT STUDENT_NAME , STUDENT_SSN 
FROM TB_STUDENT ts 
ORDER BY STUDENT_SSN DESC;


--3
SELECT STUDENT_NAME 학생이름, STUDENT_NO 학번, STUDENT_ADDRESS "거주지 주소"
FROM TB_STUDENT ts
WHERE STUDENT_NO LIKE '9%'
AND STUDENT_ADDRESS LIKE '강원도%'
OR STUDENT_ADDRESS LIKE '경기도%'
ORDER BY 1,2,3;


--4
SELECT PROFESSOR_NAME, PROFESSOR_SSN 
FROM TB_PROFESSOR tp 
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME ='법학과'
ORDER BY PROFESSOR_SSN; 



--5

SELECT STUDENT_NO , POINT 
FROM TB_GRADE tg 
WHERE CLASS_NO='C3118100'
AND TERM_NO= 200402
ORDER BY POINT DESC, STUDENT_NO;




--6
SELECT STUDENT_NO , STUDENT_NAME , DEPARTMENT_NAME
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
ORDER BY 2;


--7

SELECT CLASS_NAME , DEPARTMENT_NAME
FROM TB_CLASS tc 
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO);



--8
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS tc 
JOIN TB_CLASS_PROFESSOR tcp USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO);



--9
SELECT CLASS_NAME , PROFESSOR_NAME
FROM TB_CLASS tc 
JOIN TB_CLASS_PROFESSOR tcp USING(CLASS_NO)
JOIN TB_PROFESSOR USING(PROFESSOR_NO)
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
WHERE CATEGORY = '인문사회';


--10
SELECT STUDENT_NO 학번 , STUDENT_NAME "학생 이름" ,ROUND(AVG(POINT),1) "전체 평점"
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
JOIN TB_GRADE tg USING(STUDENT_NO)
WHERE DEPARTMENT_NAME ='음악학과'
GROUP BY STUDENT_NO, STUDENT_NAME;

--11
SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_DEPARTMENT td 
JOIN TB_STUDENT ts USING(DEPARTMENT_NO)
JOIN TB_PROFESSOR tp ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE STUDENT_NO = 'A313047';

SELECT DEPARTMENT_NAME 학과이름, STUDENT_NAME 학생이름, PROFESSOR_NAME 지도교수이름
FROM TB_STUDENT ts
JOIN TB_PROFESSOR tp ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
JOIN TB_DEPARTMENT td ON(tp.DEPARTMENT_NO  = td.DEPARTMENT_NO)
WHERE STUDENT_NO = 'A313047';

--12
SELECT STUDENT_NAME, TERM_NO "TERM_NAME"
FROM TB_STUDENT ts 
JOIN TB_GRADE tg USING(STUDENT_NO)
JOIN TB_CLASS tc USING(CLASS_NO)
WHERE TERM_NO LIKE '2007%'
AND CLASS_NAME = '인간관계론';


--13

SELECT CLASS_NAME, DEPARTMENT_NAME
FROM TB_CLASS tc 
LEFT JOIN TB_CLASS_PROFESSOR tcp USING(CLASS_NO)
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
WHERE PROFESSOR_NO IS NULL
AND CATEGORY = '예체능';


--14
SELECT STUDENT_NAME 학생이름, 
DECODE(PROFESSOR_NAME, NULL,'지도교수 미지정', PROFESSOR_NAME) 지도교수
FROM TB_STUDENT ts 
LEFT JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR tp ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY ENTRANCE_DATE;



SELECT STUDENT_NAME 학생이름, 
DECODE(PROFESSOR_NAME, NULL,'지도교수 미지정', PROFESSOR_NAME) 지도교수
FROM TB_STUDENT ts 
JOIN TB_DEPARTMENT td ON(ts.DEPARTMENT_NO=td.DEPARTMENT_NO)
LEFT JOIN TB_PROFESSOR tp ON(COACH_PROFESSOR_NO = PROFESSOR_NO)
WHERE DEPARTMENT_NAME = '서반아어학과'
ORDER BY STUDENT_NO;

--15
SELECT STUDENT_NO 학번, STUDENT_NAME 이름, DEPARTMENT_NAME "학과 이름", TRUNC(AVG(POINT),8) 평점
FROM TB_STUDENT
JOIN TB_DEPARTMENT USING(DEPARTMENT_NO)
JOIN TB_GRADE USING(STUDENT_NO)
WHERE ABSENCE_YN = 'N'
GROUP BY STUDENT_NO, STUDENT_NAME, DEPARTMENT_NAME
HAVING AVG(POINT) >= 4
ORDER BY 1;


--16
SELECT CLASS_NO , CLASS_NAME , TRUNC(AVG(POINT),8)
FROM TB_CLASS tc 
JOIN TB_GRADE tg USING(CLASS_NO)
JOIN TB_DEPARTMENT td USING(DEPARTMENT_NO)
WHERE DEPARTMENT_NAME = '환경조경학과'
AND CLASS_TYPE<>'논문지도'
GROUP BY CLASS_NO, CLASS_NAME
ORDER BY 1;







