--1
SELECT STUDENT_NO AS 학번, STUDENT_NAME AS 이름, ENTRANCE_DATE AS 입학년도
FROM TB_STUDENT ts 
WHERE DEPARTMENT_NO ='002'
ORDER BY ENTRANCE_DATE;

--2
SELECT  PROFESSOR_NAME , PROFESSOR_SSN 
FROM TB_PROFESSOR tp 
WHERE LENGTH(PROFESSOR_NAME)<>3;


--3
SELECT PROFESSOR_NAME AS 교수이름, EXTRACT(YEAR FROM SYSDATE) - SUBSTR(PROFESSOR_SSN,1,2)-1900 AS 나이
--FLOOR(MONTH_BETWEEN(SYSDATE, TO_DATE('19'||SUBSTR(PROFESSOR_SSN,1,6), 'YYYYMMDD')), /12) AS 나이
FROM TB_PROFESSOR tp
WHERE SUBSTR(PROFESSOR_SSN,8,1)='1'
ORDER BY 나이;

--4
SELECT SUBSTR(PROFESSOR_NAME,2,3) AS 이름
FROM TB_PROFESSOR tp ;


--5
SELECT STUDENT_NO, STUDENT_NAME
FROM TB_STUDENT ts 
WHERE EXTRACT(YEAR FROM ENTRANCE_DATE) - 
TO_CHAR(TO_DATE(SUBSTR(STUDENT_SSN,1,INSTR(STUDENT_SSN, '-')-1) ,'RRMMDD'), 'YYYY')>=20;
--EXTRACT(YEAR FROM TO_DATE('19'||SUBSTR(STUDENT_SSN,1,6),'YYYYMMDD'))

--6
SELECT TO_CHAR(TO_DATE('2020-12-25'), 'DAY') AS 요일
FROM DUAL;


--7
/*TO_DATE('99/10/11','YY/MM/DD'), TO_DATE('49/10/11','YY/MM/DD')은 
 * 연도 포멧팅이 YY로 2000년대이고
 * 
 * TO_DATE('99/10/11','RR/MM/DD') ,TO_DATE('49/10/11','RR/MM/DD')은 
 * 50년 이상 차이날 경우 이전 세기로 취급되므로 각각 2000년대, 1900년대이다.
 * 
 * */


--8
SELECT STUDENT_NO , STUDENT_NAME 
FROM TB_STUDENT ts 
WHERE SUBSTR(STUDENT_NO,1,1) <>'A';



--9
SELECT ROUND( AVG(POINT), 1) AS 평점
FROM TB_GRADE tg 
WHERE STUDENT_NO = 'A517178';


--10
SELECT DEPARTMENT_NO AS 학과번호, COUNT(*) AS "학생수(명)"
FROM TB_STUDENT ts 
GROUP BY DEPARTMENT_NO
ORDER BY DEPARTMENT_NO ;



--11
SELECT COUNT(*)
FROM TB_STUDENT ts 
WHERE COACH_PROFESSOR_NO IS NULL;


--12
SELECT SUBSTR(TERM_NO,1,4) AS 년도, ROUND(AVG(POINT),1) AS "년도 별 평점"
FROM TB_GRADE tg 
WHERE STUDENT_NO ='A112113'
GROUP BY SUBSTR(TERM_NO,1,4)
ORDER BY 1;



--13

SELECT DEPARTMENT_NO AS 학과코드명, COUNT(*) "휴학생 수"
FROM TB_STUDENT ts
WHERE ABSENCE_YN <>'N'
GROUP BY DEPARTMENT_NO 
ORDER BY 1;



--14
SELECT STUDENT_NAME AS 동일이름, COUNT(*) AS "동명인 수"
FROM TB_STUDENT ts 
GROUP BY STUDENT_NAME
HAVING COUNT(*)>1
ORDER BY STUDENT_NAME;


--15
SELECT NVL(SUBSTR(TERM_NO,1,4), ' ' ) AS 년도, SUBSTR(TERM_NO,5,2) AS 학기, ROUND(AVG(POINT),1) AS 평점
FROM TB_GRADE tg 
WHERE STUDENT_NO ='A112113'
GROUP BY ROLLUP (SUBSTR(TERM_NO,1,4), SUBSTR(TERM_NO,5,2));


